cred_repo: cf-pub-tools/bookbinder-ci-credentials
book_repo: cf-pub-tools/small-book

public_host: small-book.cfapps.io

sections:
- repository:
    name: cf-pub-tools/tiny-section
  directory: docs-are-small
- repository:
    name: cloudfoundry/docs-dev-guide
  directory: devguide-is-cool
